version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
      target: dev
    container_name: devlocator
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/go/src/app
    ports:
      - "8000:8000"
  
  db:
    image: mysql:8.1.0
    container_name: devlocator-db
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3307:3306
    healthcheck:  # healthcheckの設定
      test: mysqladmin ping -h 127.0.0.1 -u ${MYSQL_USER} -p ${MYSQL_PASSWORD}  # MySQLサーバーへのping
      interval: 10s  # 10秒ごとにhealthcheckを実行
      timeout: 5s   # healthcheckのタイムアウト時間
      retries: 3     # 失敗時のリトライ回数