version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
      target: dev
    container_name: devlocator
    volumes:
      - .:/go/src/app
    ports:
      - "8000:8000"
  
  db:
    image: mysql:8.1.0
    container_name: devlocator-db
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3307:3306