openapi: 3.1.0
x-stoplight:
  id: h58mydtwhxhb6
info:
  title: devlocator
  version: '1.0'
  summary: devlocatorのバックエンドAPI仕様書
servers:
  - url: 'http://localhost:8080'
    description: devlocator-api
paths:
  /api/events:
    get:
      summary: search events
      responses:
        '200':
          $ref: '#/components/responses/search_event'
        '400':
          $ref: '#/components/responses/400_bad_request'
        '401':
          $ref: '#/components/responses/401_unauthorized'
        '403':
          $ref: '#/components/responses/403_forbidden'
        '404':
          $ref: '#/components/responses/404_not_found'
        '500':
          $ref: '#/components/responses/500_internal_server_error'
      operationId: get-api-event
      x-stoplight:
        id: 17zzfhzdbqey3
      parameters:
        - $ref: '#/components/parameters/event_id'
        - $ref: '#/components/parameters/keyword'
        - $ref: '#/components/parameters/search_method'
        - $ref: '#/components/parameters/date'
      description: イベント検索
      tags:
        - event
    parameters: []
  /api/events/bookmark:
    put:
      summary: bookmark
      operationId: put-api-event-bookmark
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/400_bad_request'
        '401':
          $ref: '#/components/responses/401_unauthorized'
        '403':
          $ref: '#/components/responses/403_forbidden'
        '404':
          $ref: '#/components/responses/404_not_found'
        '500':
          $ref: '#/components/responses/500_internal_server_error'
      x-stoplight:
        id: 2o3tql7ca9bhw
      description: イベントのブックマーク
      security:
        - bearer: []
      requestBody:
        $ref: '#/components/requestBodies/bookmark'
      tags:
        - event
    parameters: []
  '/api/events/{eventId}':
    parameters:
      - schema:
          type: string
        name: eventId
        in: path
        required: true
    get:
      summary: detail event
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/detail_event'
        '400':
          $ref: '#/components/responses/400_bad_request'
        '401':
          $ref: '#/components/responses/401_unauthorized'
        '403':
          $ref: '#/components/responses/403_forbidden'
        '404':
          $ref: '#/components/responses/404_not_found'
        '500':
          $ref: '#/components/responses/500_internal_server_error'
      operationId: get-api-events-eventId
      x-stoplight:
        id: 2r1tqyrpcdnj5
      description: イベント詳細取得
  /api/users:
    get:
      summary: get users
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/users'
        '400':
          $ref: '#/components/responses/400_bad_request'
        '401':
          $ref: '#/components/responses/401_unauthorized'
        '403':
          $ref: '#/components/responses/403_forbidden'
        '404':
          $ref: '#/components/responses/404_not_found'
        '500':
          $ref: '#/components/responses/500_internal_server_error'
      operationId: get-api-users
      x-stoplight:
        id: 4adk0339fef3x
      description: |-
        ユーザ情報取得
        ユーザがブックマークしたイベント情報も取得？
components:
  schemas:
    Event:
      title: Event
      x-stoplight:
        id: srjfcj8ymen0e
      type: object
      description: イベントモデル
      properties:
        eventId:
          type: integer
          x-stoplight:
            id: i8qoxy40ezq6m
          description: イベントID
        title:
          type: string
          x-stoplight:
            id: 0vkc5q5wqu27x
          description: イベントタイトル
        catch:
          type: string
          x-stoplight:
            id: s9gz0bybffj3e
          description: キャッチ
        description:
          type: string
          x-stoplight:
            id: 4scuuqvzia9bw
          description: 概要
        eventUrl:
          type: string
          x-stoplight:
            id: pb3kdzvs2c0rn
          description: イベントURL
        startedAt:
          type: string
          x-stoplight:
            id: ns6qfl8omt41f
          format: date-time
          description: イベント開催日時
        endedAt:
          type: string
          x-stoplight:
            id: v6sao5cfqyoqo
          format: date-time
          description: イベント終了日時
        limit:
          type: integer
          x-stoplight:
            id: 4oaq0iya6koz0
          description: 定員
        eventType:
          type: string
          x-stoplight:
            id: x3m9t7ecapte4
          description: |-
            イベント参加タイプ
            participation: connpassで参加受付あり
            advertisement: 告知のみ
        address:
          type: string
          x-stoplight:
            id: tm2wukm9hakh9
          description: 開催場所
        place:
          type: string
          x-stoplight:
            id: y3dr7eyne1qhr
          description: 開催会場
        lat:
          type: string
          x-stoplight:
            id: 7a651kzt6i0fi
          description: 開催会場の緯度
        lon:
          type: string
          x-stoplight:
            id: ssq1crwuec2j3
          description: 開催会場の経度
        accepted:
          type: integer
          x-stoplight:
            id: 1khxzfjqo9xob
          description: 参加者数
        waiting:
          type: integer
          x-stoplight:
            id: w4v12o40ddpky
          description: 補欠者数
        updatedAt:
          type: string
          x-stoplight:
            id: zr91qssfqt0hm
          format: date-time
          description: イベント更新日時
      required:
        - eventId
        - title
        - lat
        - lon
    Error:
      title: Error
      x-stoplight:
        id: o9hdm6get7ukd
      type: object
      description: エラーモデル
      properties:
        message:
          type: string
          x-stoplight:
            id: c955mrmbinpay
          description: エラーメッセージ
        code:
          type: integer
          x-stoplight:
            id: xgz53sn6yhs48
          description: ステータスコード
        details:
          type: string
          x-stoplight:
            id: wjk09501ebrpf
          description: エラーメッセージの詳細
      required:
        - message
        - code
        - details
  parameters:
    event_id:
      name: event_id
      in: query
      required: false
      schema:
        type: string
      description: イベント毎に割り当てられた番号
    keyword:
      name: keyword
      in: query
      required: false
      schema:
        type: string
      description: キーワード
    search_method:
      name: search_method
      in: query
      required: false
      schema:
        type: string
      description: 検索条件（ORもしくはAND）
    date:
      name: date
      in: query
      required: false
      schema:
        type: string
      description: イベント開催日
  responses:
    search_event:
      description: イベント検索apiのレスポンス
      content:
        application/json:
          schema:
            type: object
            properties:
              resultsReturned:
                type: integer
                x-stoplight:
                  id: f1bi3hrp6dsyc
                description: 含まれる検索結果の件数
              events:
                type: array
                x-stoplight:
                  id: 5i5y4v2wlsxmp
                description: イベントリスト
                items:
                  x-stoplight:
                    id: u4ehflejb242e
                  type: object
                  properties:
                    eventId:
                      type: integer
                      x-stoplight:
                        id: jygioioyzvdya
                    title:
                      type: string
                      x-stoplight:
                        id: 7gryyqvevm1b8
                    eventUrl:
                      type: string
                      x-stoplight:
                        id: 4zi9v7i6r5pva
                    startedAt:
                      type: string
                      x-stoplight:
                        id: pas2of1rs81tp
                    endedAt:
                      type: string
                      x-stoplight:
                        id: kfptz6qt06gwy
                    limit:
                      type: integer
                      x-stoplight:
                        id: 7gu4vskk5zoyg
                    eventType:
                      type: string
                      x-stoplight:
                        id: skag1hzdttyx8
                    address:
                      type: string
                      x-stoplight:
                        id: dvp2jujv3reb1
                    place:
                      type: string
                      x-stoplight:
                        id: 9w0a8rx6soy7z
                    lat:
                      type: string
                      x-stoplight:
                        id: f6h8kt44jjdbz
                    lon:
                      type: string
                      x-stoplight:
                        id: ej5ueb64bfq6p
                    accepted:
                      type: integer
                      x-stoplight:
                        id: xcj4drq8y71zo
                    waiting:
                      type: integer
                      x-stoplight:
                        id: fvua7bo44sp7x
                    updatedAt:
                      type: string
                      x-stoplight:
                        id: 8fwirh5w6uxxg
                  required:
                    - eventId
                    - title
                    - lat
                    - lon
            required:
              - resultsReturned
              - events
          examples:
            Example 1:
              $ref: '#/components/examples/search_event'
      headers: {}
    users:
      description: ユーザ情報レスポンス
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
                x-stoplight:
                  id: jnm0bv9ntg9as
                description: 名前
              image:
                type: string
                x-stoplight:
                  id: xh1qqgkcqn83g
                description: googleアカウントのアイコン画像
              markedEvents:
                x-stoplight:
                  id: 3cwisos8jrt1k
                type: array
                description: ブックマークしたイベント
                items:
                  $ref: '#/components/schemas/Event'
                  x-stoplight:
                    id: 1965imic8ms7a
              firebaseUid:
                type: string
                x-stoplight:
                  id: f1gi2lmyi7556
            required:
              - name
              - markedEvents
              - firebaseUid
          examples:
            Example 1:
              $ref: '#/components/examples/users'
    400_bad_request:
      description: 400 BadRequest response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            Example 1:
              $ref: '#/components/examples/400_bad_request'
    401_unauthorized:
      description: 401 Unauthorized response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            Example 1:
              $ref: '#/components/examples/401_unauthorized'
    403_forbidden:
      description: 403 Forbidden response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            Example 1:
              $ref: '#/components/examples/403_forbidden'
    404_not_found:
      description: 404 Not Found response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            Example 1:
              $ref: '#/components/examples/404_not_found'
    500_internal_server_error:
      description: 500 Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            Example 1:
              $ref: '#/components/examples/500_internal_server_error'
    detail_event:
      description: イベント詳細レスポンス
      content:
        application/json:
          schema:
            type: object
            properties:
              resultsReturned:
                type: integer
                x-stoplight:
                  id: 8u7rzua76rbad
              events:
                type: array
                x-stoplight:
                  id: c7hbhasscuxgy
                description: イベント情報配列
                items:
                  $ref: '#/components/schemas/Event'
                  x-stoplight:
                    id: cv7bsdiffuabi
            required:
              - resultsReturned
              - events
          examples:
            Example 1:
              $ref: '#/components/examples/detail_event'
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
  examples:
    search_event:
      value:
        resultsReturned: 100
        events:
          - eventId: 364
            title: BPStudy#56
            eventUrl: 'https://connpass.com/event/364/'
            startedAt: '2012-04-17T18:30:00+09:00'
            endedAt: '2012-04-17T20:30:00+09:00'
            limit: 80
            eventType: participation
            address: 東京都豊島区東池袋1-7-12
            place: BPオフィス (日産ビルディング7F)
            lat: '35.6802361'
            lon: '139.7013085'
            accepted: 80
            waiting: 15
            updatedAt: '2012-03-20T12:07:32+09:00'
          - eventId: 364
            title: BPStudy#56
            eventUrl: 'https://connpass.com/event/364/'
            startedAt: '2012-04-17T18:30:00+09:00'
            endedAt: '2012-04-17T20:30:00+09:00'
            limit: 80
            eventType: participation
            address: 東京都豊島区東池袋1-7-12
            place: BPオフィス (日産ビルディング7F)
            lat: '35.6802361'
            lon: '139.7013085'
            accepted: 80
            waiting: 15
            updatedAt: '2012-03-20T12:07:32+09:00'
    users:
      value:
        name: takumi
        image: tttttt
        firebaseUid: 1fsdfsdfsdfsdf
        markedEvents:
          - id: 974c0a56-54d0-272e-d2c1-7069ab7d8927
            eventId: 364
            title: BPStudy#56
            catch: 株式会社ビープラウドが主催するWeb系技術討論の会
            description: 今回は「Python プロフェッショナル　プログラミング」執筆プロジェクトの継続的ビルドについて、お話しして頂きます。
            eventUrl: 'https://connpass.com/event/364/'
            startedAt: '2012-04-17T18:30:00+09:00'
            endedAt: '2012-04-17T20:30:00+09:00'
            limit: 80
            eventType: participation
            series:
              id: 1
              title: BPStudy
              url: 'https://connpass.com/series/1/'
            address: 東京都豊島区東池袋1-7-12
            place: BPオフィス (日産ビルディング7F)
            lat: '35.6802361'
            lon: '139.7013085'
            accepted: 80
            waiting: 15
            updatedAt: '2012-03-20T12:07:32+09:00'
          - id: dd626d53-2cd4-f9eb-8c75-985667f5027b
            eventId: 364
            title: BPStudy#56
            catch: 株式会社ビープラウドが主催するWeb系技術討論の会
            description: 今回は「Python プロフェッショナル　プログラミング」執筆プロジェクトの継続的ビルドについて、お話しして頂きます。
            eventUrl: 'https://connpass.com/event/364/'
            startedAt: '2012-04-17T18:30:00+09:00'
            endedAt: '2012-04-17T20:30:00+09:00'
            limit: 80
            eventType: participation
            series:
              id: 1
              title: BPStudy
              url: 'https://connpass.com/series/1/'
            address: 東京都豊島区東池袋1-7-12
            place: BPオフィス (日産ビルディング7F)
            lat: '35.6802361'
            lon: '139.7013085'
            accepted: 80
            waiting: 15
            updatedAt: '2012-03-20T12:07:32+09:00'
    400_bad_request:
      value:
        message: BadRequest
        code: 400
        details: リクエストボディ eventId が正しい形式ではありません
    bookmark:
      value:
        id: 974c0a56-54d0-272e-d2c1-7069ab7d8927
    404_not_found:
      value:
        message: NotFound
        code: 404
        details: イベントID 12345 に対応するイベントが存在しません
    403_forbidden:
      value:
        message: Forbidden
        code: 403
        details: リクエストボディ eventId が正しい形式ではありません
    401_unauthorized:
      value:
        message: Unauthorized
        code: 401
        details: アクセストークンが無効です
    500_internal_server_error:
      value:
        message: InternalServerError
        code: 500
        details: リクエスト処理中に予期しないエラーが発生しました
    detail_event:
      value:
        resultsReturned: 100
        events:
          - eventId: 364
            title: BPStudy#56
            catch: 株式会社ビープラウドが主催するWeb系技術討論の会
            description: 今回は「Python プロフェッショナル　プログラミング」執筆プロジェクトの継続的ビルドについて、お話しして頂きます。
            eventUrl: 'https://connpass.com/event/364/'
            startedAt: '2012-04-17T18:30:00+09:00'
            endedAt: '2012-04-17T20:30:00+09:00'
            limit: 80
            eventType: participation
            address: 東京都豊島区東池袋1-7-12
            place: BPオフィス (日産ビルディング7F)
            lat: '35.6802361'
            lon: '139.7013085'
            accepted: 80
            waiting: 15
            updatedAt: '2012-03-20T12:07:32+09:00'
          - eventId: 364
            title: BPStudy#56
            catch: 株式会社ビープラウドが主催するWeb系技術討論の会
            description: 今回は「Python プロフェッショナル　プログラミング」執筆プロジェクトの継続的ビルドについて、お話しして頂きます。
            eventUrl: 'https://connpass.com/event/364/'
            startedAt: '2012-04-17T18:30:00+09:00'
            endedAt: '2012-04-17T20:30:00+09:00'
            limit: 80
            eventType: participation
            address: 東京都豊島区東池袋1-7-12
            place: BPオフィス (日産ビルディング7F)
            lat: '35.6802361'
            lon: '139.7013085'
            accepted: 80
            waiting: 15
            updatedAt: '2012-03-20T12:07:32+09:00'
  requestBodies:
    bookmark:
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: string
                x-stoplight:
                  id: 6ucaldw7mya62
                description: eventsテーブルのid
            required:
              - id
          examples:
            Example 1:
              $ref: '#/components/examples/bookmark'
      description: ブックマーク追加・削除
