name: go-ci
on:
  pull_request:
    branches: [main]
      paths:
        - '**.go'
        - 'go.mod'
        - 'go.sum'
        - '.github/workflows/**'
  push:
    branches: [main]
      paths:
        - '**.go'
        - 'go.mod'
        - 'go.sum'
        - '.github/workflows/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: go build ./main.go
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: go test ./... -v

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
